mysql:
  image: mysql
  container_name: database
  ports:
    - 3306:3306
  environment:
    MYSQL_DATABASE: laravel
    MYSQL_ROOT_PASSWORD: laravel

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
  - mysql
  ports:
    - 8183:80
  environment:
    MYSQL_USERNAME: admin
    MYSQL_ROOT_PASSWORD: admin
    PMA_ARBITRARY: 1

php:
  image: php:fpm-alpine
  container_name: php
  volumes:
    - .:/var/www/laravel-docker
  entrypoint:
    - php-fpm

nginx:
  image: nginx:alpine
  container_name: nginx
  volumes_from:
    - php
  volumes:
    - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    - 8080:80
composer:
  image: composer
  ports:
    - "9001:9000"
  volumes:
    - "./composer:/composer"
  container_name: composer
  
